FROM library/ubuntu:18.04

WORKDIR  /root

ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y apt-utils

# Tools
RUN apt-get install -y vim

# Git
RUN apt-get install -y git

# Dev tools
RUN apt-get install -y libtool cmake m4
RUN apt-get install -y automake clang-format

COPY vimrc /root/.vimrc
COPY bashrc /root/.bashrc

# Expose ports
# EXPOSE 22 80 8080

ENTRYPOINT ["/bin/sh", "-c", "while true; do echo hello; sleep 60; done"]
